const quotes = [
  "“You miss 100% of the shots you don’t take.” – Wayne Gretzky",
  "“Champions keep playing until they get it right.” – Billie Jean King",
  "“Hard work beats talent when talent doesn’t work hard.” – Tim Notke",
  "“It’s not whether you get knocked down; it’s whether you get up.” – Vince Lombardi",
  "“Success isn’t owned. It’s leased. And rent is due every day.” – J.J. Watt",
  "“The difference between the impossible and the possible lies in a person’s determination.” – Tommy Lasorda",
  "“Do something today that your future self will thank you for.” – Sean Patrick Flanery",
  "“Never say never because limits, like fears, are often just an illusion.” – Michael Jordan",
  "“Pain is temporary. Quitting lasts forever.” – Lance Armstrong",
  "“It never gets easier. You just get better.” – Unknown",
  "“I’ve failed over and over and over again in my life. And that is why I succeed.” – Michael Jordan",
  "“Winning means you’re willing to go longer, work harder, and give more than anyone else.” – Vince Lombardi",
  "“If something stands between you and your success, move it. Never be denied.” – Dwayne Johnson",
  "“There may be people with more talent than you, but there’s no excuse for anyone to work harder than you do.” – Derek Jeter",
  "“Push yourself again and again. Don’t give an inch until the final buzzer sounds.” – Larry Bird",
  "“Success is no accident. It is hard work, perseverance, learning, studying, sacrifice, and most of all, love of what you are doing.” – Pelé",
  "“The only way to prove you are a good sport is to lose.” – Ernie Banks",
  "“It’s not the will to win that matters—everyone has that. It’s the will to prepare to win that matters.” – Paul Bryant",
  "“The only one who can tell you ‘you can’t win’ is you and you don’t have to listen.” – Jessica Ennis-Hill",
  "“If you train hard, you’ll not only be hard, you’ll be hard to beat.” – Herschel Walker",
  "“A champion is afraid of losing. Everyone else is afraid of winning.” – Billie Jean King",
  "“You have to expect things of yourself before you can do them.” – Michael Jordan",
  "“Age is no barrier. It’s a limitation you put on your mind.” – Jackie Joyner-Kersee",
  "“The harder the battle, the sweeter the victory.” – Les Brown",
  "“Adversity causes some men to break; others to break records.” – William Arthur Ward",
  "“Practice does not make perfect. Only perfect practice makes perfect.” – Vince Lombardi",
  "“Gold medals aren’t really made of gold. They’re made of sweat, determination, and a hard-to-find alloy called guts.” – Dan Gable",
  "“Don’t measure yourself by what you have accomplished, but by what you should have accomplished with your ability.” – John Wooden",
  "“Excellence is not a singular act but a habit. You are what you repeatedly do.” – Shaquille O’Neal",
  "“The more difficult the victory, the greater the happiness in winning.” – Pele",
  "“You can’t put a limit on anything. The more you dream, the farther you get.” – Michael Phelps",
  "“Never give up! Failure and rejection are only the first step to succeeding.” – Jim Valvano",
  "“Don’t count the days, make the days count.” – Muhammad Ali",
  "“Obstacles don’t have to stop you. If you run into a wall, don’t turn around and give up. Figure out how to climb it, go through it, or work around it.” – Michael Jordan",
  "“Success usually comes to those who are too busy to be looking for it.” – Henry David Thoreau",
  "“You have to believe in yourself when no one else does.” – Serena Williams",
  "“The only disability in life is a bad attitude.” – Scott Hamilton",
  "“I don’t count my sit-ups; I only start counting when it starts hurting because they’re the only ones that count.” – Muhammad Ali",
  "“Do not let what you cannot do interfere with what you can do.” – John Wooden",
  "“Don’t quit. Suffer now and live the rest of your life as a champion.” – Muhammad Ali",
  "“Make each day your masterpiece.” – John Wooden",
  "“To uncover your true potential, you must first find your own limits and then have the courage to blow past them.” – Picabo Street",
  "“Champions keep playing until they get it right.” – Billie Jean King",
  "“The mind is the limit. As long as the mind can envision the fact that you can do something, you can do it.” – Arnold Schwarzenegger",
  "“You have to do something in your life that is honorable and not cowardly if you are to live in peace with yourself.” – Larry Brown",
  "“Greatness is not in where we stand, but in what direction we are moving.” – Oliver Wendell Holmes",
  "“A trophy carries dust. Memories last forever.” – Mary Lou Retton",
  "“We can’t become what we need to be by remaining what we are.” – Oprah Winfrey",
  "“The best way to predict the future is to create it.” – Peter Drucker",
  "“It’s not the size of the dog in the fight, but the size of the fight in the dog.” – Mark Twain",
  "“Every strike brings me closer to the next home run.” – Babe Ruth",
  "“You win some, you lose some, but you live to fight another day.” – Unknown",
  "“Effort only fully releases its reward after a person refuses to quit.” – Napoleon Hill",
  "“You don’t have to be the best, but you have to be willing to work the hardest.” – Unknown",
  "“The more I practice, the luckier I get.” – Gary Player",
  "“Success is where preparation and opportunity meet.” – Bobby Unser",
  "“The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.” – Vince Lombardi",
  "“The will to win means nothing without the will to prepare.” – Juma Ikangaa",
  "“Don’t let what you cannot do stop you from doing what you can do.” – John Wooden",
  "“Winning isn’t everything, but wanting to win is.” – Vince Lombardi",
  "“Motivation is what gets you started. Habit is what keeps you going.” – Jim Ryun",
  "“Don’t measure yourself by what you have accomplished, but by what you should have accomplished with your ability.” – John Wooden",
  "“The only place success comes before work is in the dictionary.” – Vince Lombardi",
  "“You have to expect things of yourself before you can do them.” – Michael Jordan",
  "“A good hockey player plays where the puck is. A great hockey player plays where the puck is going to be.” – Wayne Gretzky",
  "“Some people want it to happen, some wish it would happen, others make it happen.” – Michael Jordan",
  "“If you fail to prepare, you’re prepared to fail.” – Mark Spitz",
  "“Success isn’t permanent and failure isn’t fatal.” – Mike Ditka",
  "“Do what you have to do until you can do what you want to do.” – Oprah Winfrey",
  "“Winners are not afraid of losing. But losers are.” – Robert Kiyosaki",
  "“A champion shows who he is by what he does when he thinks no one is watching.” – Unknown",
  "“Don’t be afraid to fail. Be afraid not to try.” – Michael Jordan",
  "“You don’t have to be great to start, but you have to start to be great.” – Zig Ziglar",
  "“Hard work beats talent when talent doesn’t work hard.” – Tim Notke",
  "“The difference between the impossible and the possible lies in a person’s determination.” – Tommy Lasorda",
  "“You’re never a loser until you quit trying.” – Mike Ditka",
  "“When you win, say nothing. When you lose, say less.” – Paul Brown",
  "“Every champion was once a contender that refused to give up.” – Rocky Balboa",
  "“Some people say I have attitude – maybe I do... but I think you have to.” – Venus Williams",
  "“I don’t count the sit-ups; I only start counting when it starts hurting because they’re the only ones that count.” – Muhammad Ali",
  "“I hated every minute of training, but I said, ‘Don’t quit. Suffer now and live the rest of your life as a champion.’” – Muhammad Ali",
  "“When you get knocked down, get back up and try again.” – Unknown",
  "“The greatest test of courage on earth is to bear defeat without losing heart.” – Robert Green Ingersoll",
  "“Your biggest opponent isn’t the other guy. It’s human nature.” – Bobby Knight",
  "“Be the best version of yourself in anything you do. You don’t have to live anybody else’s story.” – Steph Curry",
  "“I never worry about the problem. I worry about the solution.” – Shaquille O’Neal",
  "“Don’t practice until you get it right. Practice until you can’t get it wrong.” – Unknown",
  "“If you don’t have confidence, you’ll always find a way not to win.” – Carl Lewis",
  "“Success is the sum of small efforts, repeated day in and day out.” – Robert Collier",
  "“The more difficult the victory, the greater the happiness in winning.” – Pele",
  "“Talent wins games, but teamwork and intelligence win championships.” – Michael Jordan",
  "“The harder you work for something, the greater you’ll feel when you achieve it.” – Unknown"
];
